export const SEED_URLS: string[] = [
  // Core Web and Technology Docs
  "https://developer.mozilla.org/en-US/docs/Web",
  "https://nodejs.org/api",
  "https://spring.io/guides",
  "https://react.dev/reference/react",
  "https://vuejs.org/guide/introduction.html",
  "https://angular.dev/sitemap.xml",
  "https://nextjs.org/docs",
  "https://expressjs.com/",
  "https://nestjs.com/",
  "https://www.typescriptlang.org/docs/",
  "https://graphql.org/learn/",
  "https://grpc.io/docs/",
  "https://swagger.io/docs/",
  "https://htmx.org/docs/",
  "https://vite.dev/guide/",
  "https://webpack.js.org/concepts/",
  "https://babeljs.io/docs/",
  "https://tailwindcss.com/docs",
  "https://sass-lang.com/documentation/",
  "https://getbootstrap.com/docs/5.3/getting-started/introduction/",

  // Databases & Storage
  "https://redis.io/docs/",
  "https://www.postgresql.org/docs/",
  "https://www.mongodb.com/docs/",
  "https://sqlite.org/docs.html",
  "https://dev.mysql.com/doc/",
  "https://mariadb.org/documentation/",
  "https://cassandra.apache.org/doc/latest/",
  "https://neo4j.com/docs/",
  "https://www.elastic.co/guide/index.html",
  "https://clickhouse.com/docs/en/",
  "https://www.sqlite.org/sitemap.xml",
  "https://redis.io/sitemap.xml",
  "https://www.postgresql.org/sitemap.xml",
  "https://docs.mongodb.com/sitemap.xml",
  "https://kafka.apache.org/sitemap.xml",

  // DevOps, Containers & Infrastructure
  "https://kubernetes.io/docs/home/",
  "https://docs.docker.com/",
  "https://nginx.org/en/docs/",
  "https://httpd.apache.org/docs/",
  "https://www.terraform.io/docs",
  "https://docs.ansible.com/",
  "https://jenkins.io/doc/",
  "https://prometheus.io/docs/introduction/overview/",
  "https://grafana.com/docs/",
  "https://www.envoyproxy.io/docs",
  "https://istio.io/latest/docs/",
  "https://docs.docker.com/sitemap.xml",
  "https://kubernetes.io/sitemap.xml",
  "https://kafka.apache.org/documentation/",

  // Programming Languages
  "https://go.dev/doc/",
  "https://doc.rust-lang.org/book/",
  "https://docs.python.org/3/",
  "https://docs.oracle.com/en/java/",
  "https://learn.microsoft.com/en-us/dotnet/",
  "https://www.ruby-lang.org/en/documentation/",
  "https://www.php.net/docs.php",
  "https://kotlinlang.org/docs/home.html",
  "https://swift.org/documentation/",
  "https://dart.dev/guides",
  "https://www.scala-lang.org/api/3.x/",
  "https://elixir-lang.org/docs.html",
  "https://www.haskell.org/documentation/",
  "https://clojure.org/reference/documentation",
  "https://go.dev/sitemap.xml",

  // Cloud Platforms & Services
  "https://aws.amazon.com/developer/language/",
  "https://cloud.google.com/docs",
  "https://learn.microsoft.com/en-us/azure/",
  "https://docs.github.com/en",
  "https://docs.gitlab.com/",
  "https://stripe.com/docs",
  "https://firebase.google.com/docs",
  "https://supabase.com/docs",
  "https://vercel.com/docs",
  "https://www.netlify.com/docs/",
  "https://docs.digitalocean.com/",
  "https://stripe.com/docs/sitemap.xml",
  "https://cloud.google.com/sitemap.xml",

  // Tech Blogs & Engineering Publications
  "https://netflixtechblog.com/",
  "https://github.blog/category/engineering/",
  "https://engineering.fb.com/",
  "https://engineering.uber.com/",
  "https://discord.com/blog/engineering",
  "https://slack.engineering/",
  "https://medium.com/airbnb-engineering",
  "https://pinterest.engineering/",
  "https://engineering.linkedin.com/blog",
  "https://spotify.design/",
  "https://netflixtechblog.com/sitemap.xml",
  "https://engineering.uber.com/sitemap.xml",

  // Standards & Tech Reference Sites
  "https://www.w3.org/",
  "https://www.rfc-editor.org/",
  "https://git-scm.com/doc",
  "https://news.ycombinator.com/",
  "https://stackoverflow.com/",
  "https://www.geeksforgeeks.org/",
  "https://www.baeldung.com/",
  "https://martinfowler.com/",
  "https://highscalability.com/",
  "https://www.baeldung.com/sitemap.xml",
  "https://martinfowler.com/sitemap.xml",
  "https://highscalability.com/sitemap.xml",

  // Wikipedia Articles on Web / Computing
  "https://en.wikipedia.org/wiki/Web_crawler",
  "https://en.wikipedia.org/wiki/Search_engine",
  "https://en.wikipedia.org/wiki/Information_retrieval",
  "https://en.wikipedia.org/wiki/PageRank",
  "https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol"
];
